nixos/acme: Fix ownership error message when service user not set
The error message attempted to look at serviceConfig.User despite it
possibly not being set, resulting in:
```
       error: attribute 'User' missing
       at /nix/store/jlgjcjrx3vd9jcx2r19qb5455nw2ii62-source/nixos/modules/security/acme/mk-cert-ownership-assertion.nix:19:49:
           18|   message = "Certificate ${cert.domain} (group=${cert.group}) must be readable by service(s) ${
           19|     catSep ", " (map (svc: "${svc.name} (user=${svc.serviceConfig.User} groups=${catSep " " (svcGroups svc)})") services)
             |                                                 ^
           20|   }";
```